layouts/partials/event-tile.html

Fix link logic for events

---

layouts/partials/footer.html

This PR adds an Edit Page button to the footer of all pages except the index page.
Resolves #16

Add edit page button in footer

---

content/organizing-cfp.md

created organizing-cfp

---

content/organizing.md

We eliminated the "about section of the site. So I added it to the top of the page.

added about section to the top

---

content/organizing.md

This updates organizing page to specific templates.

Add links to the specific templates

---

content/events/index.md

Created index for NY

---

content/events/2020-bouvet-island/speakers.md

added link to speaking

---

assets/js/app.js
assets/sass/style.sass
config.toml

External link icons

---

content/code-of-conduct.md

Dan - I updated the code of conduct. LMK if these changes work.

updated code of conduct

---

.github/ISSUE_TEMPLATE/host.md

Dan - I added Eventbrite and sched as requirements. For the event request.

added event brite and sched

---

content/organizing-accept-new-proposals.md

Jennifer - I started to write this out prior to our call today. Let me know if I am missing anything.

Creating organizing process

---

assets/js/app.js
assets/sass/style.sass
layouts/partials/event-tile.html
layouts/partials/navbar.html

Navbar event redesign

---

.github/ISSUE_TEMPLATE/host.md

Under submission, checklist added "[ ] Minimum of 3 sponsors" and added "and 3 sponsors" and "Sponsor 1", "Sponsor 2", and "Sponsor 3"

Add sponsor

---

content/organizing-creating-website.md
content/organizing-marketing-promotion.md
content/organizing-registration.md

This PR fixes list formatting.
You can see broken list on, for example, https://kubernetescommunitydays.org/organizing-registration/.

Fix list formatting

---

content/organizing-registration.md

Added hard return after "Here are some other ways you can improve the registration process" so bullets would display properly

Fixed bullets with a hard return

---

assets/sass/sidebar.sass
assets/sass/style.sass
config.toml
layouts/partials/footer.html
layouts/partials/navbar.html

This PR basically goes through the current site and neat-and-tidies some of the clunkier aspects of the aesthetic.

Aesthetic adjustments

---

.github/ISSUE_TEMPLATE/host.md

added method of accepting payment

added method of accepting payment

---

.github/ISSUE_TEMPLATE/host.md

added_ktan

---

content/organizing-sponsor-prospectus.md
content/organizing.md

This isn't really a sample contract, it's a prospectus.

removing the word contract

---

assets/sass/style.sass
content/events/2020-bouvet-island/_index.md
layouts/partials/events/sponsors.html

This PR addresses #249. I'd like to improve the aesthetic here later on but this PR solves the immediate issue and unblocks some existing work.

Fix logo overflow issue

---

content/organizing-creating-website.md
layouts/partials/css.html

Enable custom CSS

---

content/organizing-creating-website.md

Add a reference to the custom.css file.

Add Custom CSS section to docs

---

assets/sass/style.sass
layouts/partials/events/sponsors.html

Signed-off-by: Dan Kohn <dan@dankohn.com>

Change sponsor class to funder to avoid adblockers

---

content/events/2020-amsterdam/prospectus.md

Fixed the coffee sponsor section in the prospectus

fix coffee sponsor

---

content/events/2020-amsterdam/_index.md

Just a minor problem with an accent

A minor issue with a stray apostrophe

---

assets/sass/sponsors.sass
assets/sass/style.sass
content/events/2020-amsterdam/_index.md
layouts/partials/events/sponsors.html

Reference implementation:
https://deploy-preview-283--kubernetes-community-days.netlify.com/events/2025-bouvet-island/

Sponsor logo sizing

---

content/events/2019-amsterdam/_index.md

Just a link from 2019 page to 2020 page

add link 2019->2020

---

content/events/2020-london/_index.md
content/events/2020-london/contact.md

Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>

Removed  "get Involved" section

---

content/events/2020-amsterdam/_index.md
content/events/2020-amsterdam/contact.md
content/events/2020-amsterdam/diversity-scholarship.md

I added two / after mailto: I thought it was working just like http:// :)

removed extra slashes

---

config.toml
content/events/2019-bouvet-island/register.md
content/events/2020-amsterdam/_index.md
content/events/2020-amsterdam/register.md
content/events/2020-amsterdam/tickets.md

I took the liberty to modify some of the common theme files to add a "Tickets" section to the navbar. I think it's a good button to have for people to immediately find the information about ticket sale.

Adding a "Tickets" section to the menubar

---

assets/js/app.js
layouts/partials/javascript.html
layouts/partials/navbar.html

jQuery is fine Alpine makes the JavaScript logic within particular components more closely wedded to the HTML, which should improve maintainability over time.

Convert site JavaScript to Alpine.js

---

content/events/2019-bouvet-island/_index.md
layouts/partials/events/dropdown.html
layouts/partials/events/menu.html
layouts/partials/navbar.html

Addresses #310.
You can see the proposed implementation in Bouvet Island: https://deploy-preview-319--kubernetes-community-days.netlify.com/events/2019-bouvet-island.

Event menu dropdown

---

content/events/2020-munich/_index.md
content/events/2020-munich/cfp.md
content/events/2020-munich/speakers.md

Fix typos and add CFP link for 2020-munich
/cc @dankohn @KTan1226

[2020-munich] Add CFP information

---

content/events/2020-london/sponsor.md

Update sponsor available number

---

content/events/2020-portland-oregon/prospectus.md

Marking Portland, OR gold sponsorships sold out

---

content/events/2020-munich/_index.md

Due to event postponement, I've updated the date of the event to Dec 1 (temporary new date).

KCD Munich: Updated event date

---

content/events/2020-bengaluru/_index.md
content/events/2020-bengaluru/cfp.md

Signed-off-by: kmova <kiran.mova@mayadata.io>

push the bengaluru kcd to dec 1st tentatively

---

content/events/2021-amsterdam/_index.md

Small addition: make it clear the CFP link changed (but submissions are kept).

2021 amsterdam cfplink

---

content/organizing.md

Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

Bevy information added to the organizing page

---

content/events/2020-paris/_index.md

Signed-off-by: Jean-Christophe Sirot <jcsirot@gmail.com>

Postpone date due to COVID-19 outbreak

---

content/events/2021-amsterdam/_index.md

With sadness we have to postpone Amsterdam again...

postponed amsterdam again

---

content/templates.md

Adds KCD Spain artwork, keynote and event playlist.

add KCD Spain resources

---

planning/organizer-mediation.md

Fixed a typo in organizer-mediation.md

Fixed a typo in organizer-mediation.md

---

planning/choosing-dates.md

Changes:
1. Fixed typo in line 9 "it is an easy trek"
2. Fixed typo in line 9 "then thesame standards apply"
3. Improved readability for other kcd's in your region considerations

chore: ✏️  Update choosing-dates.md with improved readability 

---

README.md
planning/content-management.md

Fixed several typos and spelling mistakes in the readme.md and removed one word that was in there double (line 7).

Fixed several typos and spelling mistakes
